#!/bin/bash

# exit if not root
if [ ! $(id -u) -eq 0 ]
then
	echo 'This script should be run with root permission'
	exit
fi

# variables for protocols
hp=http_proxy
hsp=https_proxy
fp=ftp_proxy
np=no_proxy
HP=HTTP_PROXY
HSP=HTTPS_PROXY
FP=FTP_PROXY
NP=NO_PROXY 


# function to set proxy in enviroment file
proxy_env()
{
	echo "SETTING ENV PROXY"
	# if None proxy then this next line is enough
	# pipe is in extended regular expr, reqs -r to enable it in GNU sed
    # Doubt: Are capital proxies needed/recommended. Don't know yet ??
	sed -r "/($hp|$HP|$hsp|$HSP|$fp|$FP|$np|$NP).*/d" /etc/environment > ./.temp_file_env;
	if [ ! $WIFI_PROXY = "None" ]
	then 
		hp_pr=http://$WIFI_PROXY/
		hsp_pr=https://$WIFI_PROXY/
		fp_pr=ftp://$WIFI_PROXY/
        np_pr="localhost,127.0.0.1"
		printf "$hp=\"$hp_pr\"\n$hsp=\"$hsp_pr\"\n$fp=\"$fp_pr\"\n$np=\"$np_pr\"\n"  >> ./.temp_file_env;
		printf "$HP=\"$hp_pr\"\n$HSP=\"$hsp_pr\"\n$FP=\"$fp_pr\"\n$NP=\"$np_pr\"\n"  >> ./.temp_file_env;
	fi
    mv ./.temp_file_env /etc/environment
}
	
# setting proxy for apt in file apt.conf
proxy_apt()
{
	echo "SETTING PROXY FOR APT, MAYBE NOT REQD FOR UBUNTU\nNECESSARY FOR KUBUNTU,XUBUNTU,LINUX MINT"
	
	# rm /etc/apt/apt.conf

	if [ $WIFI_PROXY = "None" ]
	then 
		echo clearing 95proxies file 
        printf "Acquire::http::Proxy \"false\";" > ./.temp_file_apt;
    else 
		printf "Acquire::http::Proxy \"$hp_pr\";\nAcquire::https::Proxy \"$hsp_pr\";\nAcquire::ftp::Proxy \"$fp_pr\";\n" > ./.temp_file_apt;
		echo Created apt.conf file	
	fi
	mv ./.temp_file_apt /etc/apt/apt.conf
}

if [[ ! $1 = "None" ]]
then
    PROXY_OP=$(python3 ~/.proxyhelper/surely_parallel.py | tail -1)
    echo THE OP IS $PROXY_OP
    key=$(echo $PROXY_OP | sed 's/Proxy : .*/Proxy/')
    echo THE KEY IS $key 
    if [[ $key = 'Proxy' ]]
    then
        WIFI_PROXY=$(echo $PROXY_OP | sed 's/Proxy : \(.*\)/\1/')
    else
        WIFI_PROXY=None 
    fi
else
    WIFI_PROXY=None
fi

proxy_env
proxy_apt

# We don't want to update when we are uninstalling or just resetting proxy
if [[ ! $1 = "None" ]]
then
    # Remove the line below to stop auto-update feature
    sudo ~/.proxyhelper/auto-update.sh
fi
